version: "3.7"
networks:
  merginmaps:

services:
  db:
    image: postgis/postgis:14-3.4
    container_name: merginmaps-db
    restart: always
    ports:
      - "5432:5432"
    networks:
      - merginmaps
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./mergin_db:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: merginmaps-redis
    restart: always
    networks:
      - merginmaps
  server-gunicorn:
    image: server-gunicorn
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: merginmaps-server
    restart: always
    volumes:
        - ./projects:/data
    env_file:
      - .prod.env
    depends_on:
      - db
      - redis
    command: ["gunicorn --config config.py application:application"]
    networks:
      - merginmaps
  celery-beat:
    image: celery-beat
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: celery-beat
    env_file:
      - .prod.env
    depends_on:
      - redis
      - server-gunicorn
    command: ["celery -A application.celery beat --loglevel=info"]
    networks:
      - merginmaps
  celery-worker:
    image: celery-worker
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: celery-worker
    env_file:
      - .prod.env
    depends_on:
      - redis
      - server-gunicorn
      - celery-beat
    command: ["celery -A application.celery worker --loglevel=info"]
    networks:
      - merginmaps
  web:
    image: merginmaps-frontend
    build:
      context: ./web-app
      dockerfile: Dockerfile
    container_name: merginmaps-web
    restart: always
    depends_on:
      - server-gunicorn
    links:
      - db
    volumes:
      - ./projects:/data  # map data dir to host
    ports:
      - "8080:8080"
    networks:
      - merginmaps
